[c]
dbHost = "127.0.0.1"
dbPort = "3306"
dbUser = "root"
dbPass = "123456"
dbName = "test"
dbType = "mysql"
binlogDbs = ["test"]
binlogTbs = {"test.copy"="t"}
binlogDbHost = "127.0.0.1"
binlogDbUser = "root"
binlogDbPass = "123456"
bulkSize = 128
flushBulkTime = "500ms"
dataDir = "./var"
statAddr = "127.0.0.1:11800"
serverID = 11102