[database]
dbHost = "127.0.0.1"
dbPort = "3306"
dbUser = "root"
dbPass = "123456"
dbName = "test"
dbType = "mysql"
binlogDbs = ["tiger"]
binlogTbs = {"t.copy"="t","t.trade_account"="t"}
binlogDbHost = "127.0.0.1"
binlogDbUser = "root"
binlogDbPass = "123456"

[tables]
    [tables.copy]
